pipeline {
  agent any

  environment {
    AWS_REGION = "ap-south-1"
    ECR_REPO = "200901485389.dkr.ecr.ap-south-1.amazonaws.com/rapy-ecr"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build and Test') {
      steps {
        sh 'cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn clean package'
      }
    }

    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://34.201.116.83:9000"
      }
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          sh '''
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
          mvn sonar:sonar \
          -Dsonar.login=$SONAR_AUTH_TOKEN \
          -Dsonar.host.url=${SONAR_URL}
          '''
        }
      }
    }

    stage('Build & Push Image to ECR') {
      steps {
        sh '''
        aws ecr get-login-password --region ${AWS_REGION} \
        | docker login --username AWS --password-stdin ${ECR_REPO}

        cd java-maven-sonar-argocd-helm-k8s/spring-boot-app
        docker build -t ${ECR_REPO}:${BUILD_NUMBER} .
        docker push ${ECR_REPO}:${BUILD_NUMBER}
        '''
      }
    }

    stage('Update Helm Values') {
      steps {
        withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
          sh '''
          git config user.name "Jenkins"
          git config user.email "jenkins@ci.com"

          sed -i "s/tag:.*/tag: \\"${BUILD_NUMBER}\\"/" \
          java-maven-sonar-argocd-helm-k8s/helm/spring-boot-app/values.yaml

          git add java-maven-sonar-argocd-helm-k8s/helm/spring-boot-app/values.yaml
          git commit -m "Update image tag to ${BUILD_NUMBER}"
          git push https://${GITHUB_TOKEN}@github.com/chanducherry911/Jenkins-Zero-To-Hero.git main
          '''
        }
      }
    }
  }
}
